import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/sections/Header";
import { Footer } from "@/sections/Footer";
import { Preloader } from "@/hooks/Preloader";

const DMSans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="" lang="en">
      <body
        className={`${DMSans.variable} antialiased bg-sky-700`}
      >
        <Preloader>
          <Header />
          <div>
            {children}
          </div>
          <Footer />
        </Preloader>
      </body>
    </html>
  );
}
