import { DM_Sans } from "next/font/google";
import "./globals.css";

const DMSans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="" lang="en">
      <body
        className={`${DMSans.variable}  antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
